default['ruby-env']['user'] = 'vagrant'
default['ruby-env']['group'] = 'vagrant'
default['ruby-env']['version'] = '2.3.0'
default['ruby-env']['rbenv_url'] = 'https://github.com/rbenv/rbenv.git'
default['ruby-env']['ruby-build_url'] = 'https://github.com/rbenv/ruby-build.git'
